Header header                           # local time stamp
uint16 device_id                        # specific device id
uint16 error_code                       # error code of balise reader (0 = no error)
uint16 nid_c                            # country code of passed balise
uint16 nid_bg                           # balise group id of passed balise
uint16 n_pig                            # position in group of passed balise
uint16 n_total                          # number of balises in group
uint16 m_dup                            # number of duplicates
